config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/custom_dashboard'

  devise_for :users

  # Routes pour les utilisateurs (visiteurs et locataires/propriétaires)
  # devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :stars, only: [:index, :show, :new, :create] do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [] do
    member do
      patch :custom_accept
      patch :custom_reject
    end
  end
  get '/dashboard', to: 'dashboard#custom_dashboard', as: :dashboard

  # Routes pour les favoris
  # resources :favorites, only: [:index, :create, :destroy]

  # Page de contacts, merci, etc.
  # get '/contact', to: 'pages#contact', as: :contact
  # get '/thanks', to: 'pages#thanks', as: :thanks

  
end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true


end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @stars = Star.all
  end

  def show
    @star = Star.find(params[:id])
  end

  def new
    @star = Star.new
  end

  def create
    @star = Star.new(star_params)
    @star.user = current_user
    if @star.save
      redirect_to stars_path, notice: "Astre créé avec succès"
    else
      render :new, alert: "Erreur lors de la création"
    end
  end

  private

  def star_params
    params.require(:star).permit(:name, :description, :category, :price, :photo)
  end


end

app/views/stars/index.html.erb
<div class="container">
  
  <h1>Tous les astres</h1>

  <div class="row">
    <% @stars.each do |star| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <% if star.photo.attached?%>
              <%= cl_image_tag star.photo.key, width: 200, height: 200, crop: :fill %>
            <% elsif star.image_url.present? %>
              <%= image_tag star.image_url, width: 200, height: 200, crop: :fill %>
            <% else %>
              <%= image_tag "default_image.jpg", width: 200, height: 200, alt: "Image par défaut" %>
            <% end %>
            <h1 class="card-title pt-3"><%= star.name %></h1>
            <p class="card-text">
              <%= star.category %>
            </p>
            <%= link_to "Réserver", star_path(star), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div id="custom-button-plus">
    <%= link_to "+", new_star_path, class: "btn btn-primary" %>
  </div>

</div>

app/views/stars/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="form-card">
      <h1><i class="fas fa-rocket"></i>Créer un nouvel astre</h1>

      <%= simple_form_for @star, url: stars_path do |f| %>
        <div class="form-group container-left">
          <%= f.input :category,
                      label: "Catégorie <i class='fas fa-list-ul'></i>".html_safe,
                      collection: ["Astéroïde", "Comète", "Etoile", "Planète", "Satellite", "Trou noir"],
                      prompt: "Selectionner une catégorie" %>
        </div>

        <div class="form-group container-left">
          <%= f.input :name,
                      label: "Nom de votre astre <i class='fas fa-star'></i>".html_safe %>
        </div>

        <div class="form-group container-left">
          <%= f.label :description, "<i class='fas fa-pen'></i> Description".html_safe %>
          <%= f.text_area :description, class: "form-control", rows: 4 %>
        </div>

        <div class="form-group container-left">
          <%= f.input :price,
                      label: "Prix par nuit en <i class='fas fa-euro-sign'></i>".html_safe %>
        </div>

        <div class="form-group container-left">
          <%= f.input :photo,
                      as: :file,
                      label: "Photo de l'astre <i class='fas fa-camera'></i>".html_safe %>
        </div>

        <button class="btn-cosmic">
          <i class="fas fa-paper-plane"></i> Créer
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/stars/show.html.erb
<div class="show-page">
  <div class="container">
    <div class="form-container">
      <div class="form-card">

        <div class="form-group text-center">
          <h2 class="fw-bold" style="color: #64ffda;" ><%= @star.name %></h2>


          <% if @star.photo.attached?%>
            <div class="d-flex justify-content-center mb-3">
              <%= cl_image_tag @star.photo.key, crop: :fill, class: "adaptive-image" %>
            </div>
          <% elsif @star.image_url.present? %>
            <div class="d-flex justify-content-center mb-3">
              <%= image_tag @star.image_url, crop: :fill, class: "adaptive-image" %>
            </div>
          <% else %>
            <div class="d-flex justify-content-center mb-3">
              <%= image_tag "default_image.jpg", alt: "Image par défaut" %>
            </div>
          <% end %>
        </div>

  <p></p>
      <div class="form-group text-center">
        <h2 class="fw-bold" ><%= @star.category %>
      </div>
  <p></p>
          <div class="form-group">
          <p><%= @star.description %></p>
          </div>
  <p></p>
          <div class="form-group">
          <h4 class="fw-bold" ><%= @star.price %> € / nuit</h4>
          </div>

          <p></p>
          <!-- unless @star.user==current_user -->



            <h1><i class="fas fa-rocket"></i>Réservez votre séjour</h1>
            <%= form_with model: [@star, Reservation.new], local: true do |f| %>
            <div class="d-flex justify-content-center">
              <div class="form-group me-3 ">
                <%= f.label :start_date, "Date de début", class: "text-center w-100" %>
                <%= f.date_field :start_date, class: "form-control w-100 mx-auto" %>
              </div>

              <div class="form-group">
                <%= f.label :end_date, "Date de fin", class: "text-center w-100" %>
                <%= f.date_field :end_date, class: "form-control w-100 mx-auto" %>
              </div>
              </div>

              <div class="form-group">

                <%# <p>Total : <span id="total-price">0</span>€</p> %>
              </div>


              <div class="text-center d-flex justify-content-center align-items-center">
                <%= link_to "Revenir aux astres", stars_path, class: "btn-cosmic me-2 align-self-stretch" %>
                <%= f.submit "Réserver", class: "btn-cosmic align-self-stretch " %>
                <% end %>
              </div>

        </div>
      </div>
    </div>
  </div>
</div>